### ISSUE TITLE
Face segmentation

### ISSUE THREAD

**Issue by gopi77** [akirasosa/mobile-semantic-segmentation#12]
Hi

The ppm files of LFW dataset has face as green, hair as red & remaining area as blue.
![image](https://user-images.githubusercontent.com/12639784/34264772-ef0b67c0-e699-11e7-8f6b-7afcfb94beee.png)

Suppose if I want to train the model for face segmentation, what are the changes need to be done?
Please let me know.

Regards
Gopi. J

**Comment by akirasosa** [comment]
@gopi77 
Here, it's getting R channel from mask image.
https://github.com/akirasosa/mobile-semantic-segmentation/blob/master/data.py#L28

So, you will change it to get G channel...
```python
    mask_iter = mask_gen.flow(np.expand_dims(masks[:, :, :, 1], axis=4),
                              # use same seed to apply same augmentation with image
                              seed=seed)
```

**Comment by gopi77** [comment]
Thanks :)

**Comment by sasikiran** [comment]
@akirasosa Similar question: If I have to make the network detect an object, say an airplane. I will create a dataset with 2000 images where airplanes are masked in red, and the remaining part of the scene is in blue. If I train this network on that dataset, will it be able to segment airplanes?

**Comment by akirasosa** [comment]
@sasikiran It would be possible. But creating binary masks is simpler in your case.

**Comment by sasikiran** [comment]
@akirasosa thanks. I don't think creating the dataset isn't that simple. Our designer is saying he would be able to do the masking part about 10 images in a single day and hence it would take 200 man days of effort to create a 2000 image dataset. These 2000 images would be taken from ms coco dataset.

**Comment by akirasosa** [comment]
@sasikiran 
Ah, sorry. What I mean is that red and green are not necessary. You can use binary image instead. The only reason I use RGB mask is LFW provides it as RGB mask...

In the case of airplane, situation may be different with hair. PSPNet like model may work better than  UNet like model.

**Comment by sasikiran** [comment]
Thank you!
  
  
  
 - Sasi     
  

  
  
>

**Comment by sectoreight** [comment]
@akirasosa Just want to follow up on your last point. I have the following binary ppm image. 
![image](https://user-images.githubusercontent.com/35932844/35527108-85c3f1f2-04de-11e8-992b-e7c176adb27b.png)

When I try to run the train_full.py script, it produces the error below. I suppose the code needs changes to move from RGB to binary - could you point to exactly what those need to be? Thanks!

`ValueError: ('Input data in 'NumpyArrayIterator' should have rank 4. You passed an array with shape', (80, 1, 1024))`

**Comment by akirasosa** [comment]
@sectoreight 
Did you get the error on https://github.com/akirasosa/mobile-semantic-segmentation/blob/master/data.py#L28 , right?

```masks[:, :, :, 0]``` expects something like (m, h, w, 3) as masks. It would be the meaning of ```should have rank 4``` on the error. But your array have the shape ```(80, 1, 1024)```.

**Comment by sectoreight** [comment]
The error's actually on a different line. Here's the entire log.

```
~/Developer/mobile-semantic-segmentation$ python train_full.py --img_file=data/images-1024.npy --mask_file=data/masks-1024.npy

Using TensorFlow backend.
Traceback (most recent call last):
  File "train_full.py", line 96, in <module>
	train(**vars(args))     
  File "train_full.py", line 21, in train
	train_gen, validation_gen, img_shape = load_data(img_file, mask_file)
  File "/home/sectoreight/Developer/mobile-semantic-segmentation/data.py", line 71, in load_data
	mask_gen=train_mask_gen)
  File "/home/sectoreight/Developer/mobile-semantic-segmentation/data.py", line 30, in _create_datagen
	seed=seed)
  File "/home/sectoreight/anaconda2/lib/python2.7/site-packages/keras/preprocessing/image.py", line 526, in flow
	save_format=save_format)
  File "/home/sectoreight/anaconda2/lib/python2.7/site-packages/keras/preprocessing/image.py", line 888, in __init__
	'with shape', self.x.shape)
ValueError: ('Input data in `NumpyArrayIterator` should have rank 4. You passed an array with shape', (80, 1, 1024))
```

I would like to be able to use binary PPM files as masks. How do I do that? I'm referring to your earlier comment on using [binary files](https://github.com/akirasosa/mobile-semantic-segmentation/issues/12#issuecomment-356929447).

**Comment by akirasosa** [comment]
@sasikiran 
May I ask the shape of ```data/masks-1024.npy```?

**Comment by sasikiran** [comment]
n, 224, 224, 3
  

  
where n is the number of samples and in our case it’s 1024. 224 is the width and height of the image. 3 is the number of channels.
  
  
  
 - Sasi     
  

  
  
>

**Comment by sasikiran** [comment]
The back story is, we initially wanted to segment airplanes. Later, we thought of doing humans. For this, we downloaded about 1000 images from various datasets. Then, got someone who knows Photoshop to mask out everything in the image to 'blue' and let the human remain in 'red'.

Sadly, after training 250 epochs, we realized it is picking up 'red's from the original image instead of the entire mask. For example, if an image has a red flower or a red 'stop' sign, it is trying to learn those red things instead of the red masks added to humans.

Somewhere, something went wrong.

**Comment by akirasosa** [comment]
Ah! So sorry. I made mistake @sectoreight with @sasikiran ...

@sectoreight
May I ask the shape of ```data/masks-1024.npy```?

**Comment by mdramos** [comment]
@sasikiran, any solution to your issue you last stated? @akirasosa any insight as to what his issue may be?

**Comment by sasikiran** [comment]
I don’t have any issues 🙂

Thanks.

- Sasi

**Comment by mdramos** [comment]
@sasikiran on Jan 30, you stated that "Somewhere, something went wrong.", where training had picked up red in the original image vs mask. Im just looking for insight or if you found the problem/solution?

**Comment by sasikiran** [comment]
The network didn't learn much and had errors because the custom dataset
provided for the training was total junk. There was no way a network would
learn something out of it and hence the results were very erroneous.

**Comment by akashdexati** [comment]
@akirasosa 
Is their a way in the current process to **build a model which can mark both the green & red pixels in image**?

**Comment by ldenoue** [comment]
@akirasosa you wrote that for airplanes PSPNet could be better than UNet. For segmenting a person (not just a face+hair), do you think UNet is a good pick? Even when the person has arms up in the air? I've tested DeepLabv3+ and Mask R-CNN. DeepLabv3+ gives good results but it probably won't run on mobile. That's why I got interested in UNet. Another post mentions using Tiramisu (FC-DenseNets) to [remove background of portrait photos](https://towardsdatascience.com/background-removal-with-deep-learning-c4f2104b3157) which is still up-body, not full body, so less variations.
Thanks for your input.

**Comment by akirasosa** [comment]
@akashdexati 
Yes. It is a multi class semantic segmentation.

@ldenoue
Though I'm not sure that U-Net works well in your case, one of the advantages of U-Net is that it's easy to train. You will be able to get result soon. So, I recommend you to just try.

**Comment by ldenoue** [comment]
to get face I understand I can put 1 instead of 0.
But to get both, what code should I use?
