### ISSUE TITLE
Matching shapes

### ISSUE THREAD

**Issue by arnonkahani** [akirasosa/mobile-semantic-segmentation#13]
First of all thanks for this great repo and project.

I'm using an image of the size 240 and not 128 and when running the train_full script or any other method of training I receive the following error in the net instantiation (building) procedure:

`ValueError: `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 16, 16, 512), (None, 15, 15, 512)]`

This error happens when the following layer is constructed
```
up1 = concatenate([
        Conv2DTranspose(filters, (2, 2), strides=(2, 2), padding='same')(b13),
        b11,
    ], axis=3)
```

Any idea why? or how to solve it?

Furthermore how would you suggest that use the net for arbitrary size of an image (w,h) where w != h

**Comment by akirasosa** [comment]
@arnonkahani 
What size is your input image? I remember that it must be divided by 32. For example, 128, 160, 192 and 224 are OK.

**Comment by arnonkahani** [comment]
I managed to make it work for my use case , thanks for the help.
