### ISSUE TITLE
the last depthwise_conv_block(b18)

### ISSUE THREAD

**Issue by stainless-steel-rat** [akirasosa/mobile-semantic-segmentation#16]
I noticed that the last depthwise_conv_block(b18) is annotated. You used a standard conv layer  to replace it. This standard conv layer cost about 20% computation.  So why not use depthwise_conv_block as above layers?

**Comment by stainless-steel-rat** [comment]
@akirasosa 
emm, thanks for the response. there is something wrong in my calculations indeedly, the percentage is lower than 20%. But the considering the larger size of  feature maps on the edge, the cost may also high. Does the reason of  using standard conv for a better performance?

**Comment by akirasosa** [comment]
@stainless-steel-rat 
Not so much reason. The original MobileNets uses conv block at 1st block. So, I made it symmetric.
