### ISSUE TITLE
Use the ./run.sh script to download data?

### ISSUE THREAD

**Issue by saeed68gm** [akirasosa/mobile-semantic-segmentation#18]
When I try to run it I get the error: 
`./run.sh: line 6: S3_BUCKET: unbound variable`
Do I have to set this as global var? Can you provide it?
Thanks

**Comment by akirasosa** [comment]
@saeed68gm 
You need to specify your own bucket.
```S3_BUCKET=s3://your-bucket/ ./run.sh```

**Comment by saeed68gm** [comment]
Sorry for noob question. Never worked with AWS, I will try that.

Thank you
