### ISSUE TITLE
Training Issue

### ISSUE THREAD

**Issue by shadow111** [akirasosa/mobile-semantic-segmentation#19]
when i run this command 
`python train_full.py \ --img_file=/path/to/images.npy \ --mask_file=/path/to/masks.npy`

i got this error:

`Traceback (most recent call last):
  File "train_full.py", line 96, in <module>
    train(**vars(args))
  File "train_full.py", line 21, in train
    train_gen, validation_gen, img_shape = load_data(img_file, mask_file)
  File "/home/lafi/Desktop/HairSegmentation/mobile-semantic-segmentation-master/data.py", line 60, in load_data
    train_img_gen.fit(images)
  File "/usr/local/lib/python2.7/dist-packages/keras/preprocessing/image.py", line 675, in fit
    'Got array with shape: ' + str(x.shape))
ValueError: Input to `.fit()` should have rank 4. Got array with shape: (0,)
`
Please how i can fix it
Thank you
Lafi

**Comment by edumucelli** [comment]
Are you using the placeholder path `path/to/images.npy`? You should replace it by your actual path.

**Comment by AlexRablau** [comment]
I am having the same issue.

I do use the correct paths. Without the correct paths it does not even get this far.

I am using python3. Could that be the issue?
