### ISSUE TITLE
Script to evaluate MobileUNet

### ISSUE THREAD

**Issue by kushagraagrawal** [akirasosa/mobile-semantic-segmentation#21]
Hi, could you provide a script to evaluate MobileUNet? I have trained the model and wanted to evaluate the same. Thanks

**Comment by akirasosa** [comment]
I have rewrite code using PyTorch. Please refer the notebook below about evaluation.
https://github.com/akirasosa/mobile-semantic-segmentation/blob/master/eval_unet.ipynb
