### ISSUE TITLE
how to fine-tune

### ISSUE THREAD

**Issue by zhaoyk1986** [akirasosa/mobile-semantic-segmentation#23]
hey, after run train_full.py, I got good effect, but not good enough.
when I tried 
#python train_top_model.py \
#  --img_file=/tmp/images.npy \
#  --mask_file=/tmp/masks.npy

#python train_fine_tune.py \
#  --img_file=/tmp/images.npy \
#  --mask_file=/tmp/masks.npy \

I got terrible effect...
I want to know the correct train method.

**Comment by akirasosa** [comment]
I have removed these files for simplicity. It would have no problem just using https://github.com/akirasosa/mobile-semantic-segmentation/blob/master/train_unet.py .
