### ISSUE TITLE
pred.py question

### ISSUE THREAD

**Issue by ldenoue** [akirasosa/mobile-semantic-segmentation#25]
When I run pred.py and save the plt, I get these kinds of predicted images, which are not clean like in your github
![image](https://user-images.githubusercontent.com/149561/40831635-cc3e727c-6589-11e8-83e6-57f81f6ac9ca.png)

![image](https://user-images.githubusercontent.com/149561/40831666-e3e91b70-6589-11e8-9483-54c7c5916913.png)

Any idea?

**Comment by xiaoxiongguilai** [comment]
hi  How do you get to the model **224_1_1.h5**？ Could you share it  with me？

**Comment by ldenoue** [comment]
Check the url Base_weight_path in this code: it points to the files where Keras downloads the H5 model files
https://github.com/fchollet/deep-learning-models/blob/master/mobilenet.py

**Comment by ldenoue** [comment]
Here is the page that lists them all:
https://github.com/fchollet/deep-learning-models/releases/

**Comment by akirasosa** [comment]
I have rewrite code using PyTorch. It's simpler than before so that I may solve your problem. Please take a look.
