### ISSUE TITLE
about the Version of keras and tensorflow 

### ISSUE THREAD

**Issue by hzwangjl** [akirasosa/mobile-semantic-segmentation#28]
`python train_full.py --img_file=data/images-128.npy --mask_file=data/masks-128.npy`

> ... ...
  File "/home/.local/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 1376, in __init__
    layer.outbound_nodes.append(self)
AttributeError: 'Activation' object has no attribute 'outbound_nodes'

hi， I run the training code above，got an error，could tell me the version of keras and tensorflow ？Thank you!
My Version:  Keras:2.2.0   Tensorflow:1.8.0

**Comment by saurabbhsp** [comment]
Hi,
I had the same issue. Not sure why this is happening but downgrading to 2.1.1 solved this issue for me. PS:- I am also using tensorflow 1.8.0

**Comment by akirasosa** [comment]
Hi, I have rewrite code using PyTorch 0.4.1. It's much simpler than before.
