### ISSUE TITLE
how would we generate ppm for custom sets?

### ISSUE THREAD

**Issue by iChiaGuo** [akirasosa/mobile-semantic-segmentation#30]
how would we generate ppm for custom sets?

**Comment by akirasosa** [comment]
Hi, I have rewrite code using PyTorch. Current code is simpler than before. About loading images, please refer following codes.

https://github.com/akirasosa/mobile-semantic-segmentation/blob/master/dataset.py
https://github.com/akirasosa/mobile-semantic-segmentation/blob/master/train_unet.py#L38
