### ISSUE TITLE
Is the inference time of the model related to the parameter quantity of the model?

### ISSUE THREAD

**Issue by InstantWindy** [akirasosa/mobile-semantic-segmentation#32]
How do you calculate the GFLOPS of a model? The less the parameter quantity of the model, the shorter the inference time of the model?

**Comment by akirasosa** [comment]
I have rewrite code using PyTorch. It looks that there are some tools to calculate GFLOPS in PyTorch.

* https://github.com/Lyken17/pytorch-OpCounter

> The less the parameter quantity of the model, the shorter the inference time of the model?

Generally speaking, Yes. Please take a look at my article about more detail.
[Real-Time deep learning in mobile application](https://medium.com/vitalify-asia/real-time-deep-learning-in-mobile-application-25cf601a8976)
