### ISSUE TITLE
Why my mlmodel file is so large?

### ISSUE THREAD

**Issue by summershenshen** [akirasosa/mobile-semantic-segmentation#33]
Hello, I convert my pre-trained model mu_224.h5 to mu_224.mlmodel by your coreml-converter.py script, then I get a 22.8M file. However, I git clone the https://github.com/vfa-tranhv/MobileAILab-HairColor-iOS.git and find the hair mlmodel is only 6.8M. Do anyone knows why?

**Comment by VincentCheng1995** [comment]
I think maybe your model before conversion is too large. Or in  the converting process, CoreML will do some compression to the model, that depends on the parameters you pass to it. Check this: https://www.appcoda.com/coreml2/

**Comment by akirasosa** [comment]
@summershenshen It's because https://github.com/vfa-tranhv/MobileAILab-HairColor-iOS.git uses different input size and alpha.
