### ISSUE TITLE
How to calculate the mean and std value?

### ISSUE THREAD

**Issue by summershenshen** [akirasosa/mobile-semantic-segmentation#34]
Hello, in the data.py script, the standardize function is as below:
def standardize(images, mean=None, std=None):
    if mean is None:
        # These values are available from all images.
        mean = [[[29.24429131, 29.24429131, 29.24429131]]]
    if std is None:
        # These values are available from all images.
        std = [[[69.8833313, 63.37436676, 61.38568878]]]
    x = (images - np.array(mean)) / (np.array(std) + 1e-7)
    return x
But I calculate the mean and std value of three channels of all the images respectively by np.mean() and np.std() , the result is just not the value above. Do anyone knows how to calculate the mean and std value ?

**Comment by akirasosa** [comment]
I have rewrite code. And I just use minmax scale now. Performance does not change as before.
