### ISSUE TITLE
ImportError: cannot import name 'relu6'

### ISSUE THREAD

**Issue by nemanjaq** [akirasosa/mobile-semantic-segmentation#35]
Hi,

with Keras 2.2.2, there is problem importing DepthwiseConv2D and relu6 in MobileUNet.py

DepthwiseConv2D can be probably imported from keras.layers, but I don't know where to find relu6.

**Comment by brucechou1983** [comment]
relu6 is just normal ReLU with max_value=6

**Comment by nemanjaq** [comment]
I've realized that, but thanks anyway :)

Added following instead import
`def relu6(x):
    return K.relu(x, max_value=6)`

**Comment by akirasosa** [comment]
Thanks @nemanjaq 

Now, I have rewrite code using PyTorch. Then, everything is simpler than before. There is no such problems anymore.
