### ISSUE TITLE
Is there a way to test the trained model on a single image ?

### ISSUE THREAD

**Issue by dmaugis** [akirasosa/mobile-semantic-segmentation#38]
Is there a way to test the trained model on a single image ? I m ok with writing a script if needed, only I do not know much about tensorflow, so I do not know where to begin with.
Thanks

**Comment by akirasosa** [comment]
Hi,

I rewrite code by using PyTorch. You can refer this notebook to predict specific images.
https://github.com/akirasosa/mobile-semantic-segmentation/blob/master/eval_unet.ipynb

**Comment by joel1895** [comment]
Hi, the link that you mentioned is not working. Can you provide an alternate link?
