### ISSUE TITLE
How long to train the model?

### ISSUE THREAD

**Issue by normandra** [akirasosa/mobile-semantic-segmentation#43]
I'm planning on mimicking your architecture  on the cityscapes dataset. Do you mind sharing some details on the training phase? ( Hardware / how long).

**Comment by akirasosa** [comment]
No problem.

It takes about 30 min to run 80 epochs with 1080 ti.

**Comment by normandra** [comment]
@akirasosa Thanks, I tried the model from the develop branch and ported it to android. It didn't perform that well. How much of an improvement has there been between that branch (keras/tf implementation) and your pytorch implementation?

**Comment by normandra** [comment]
nevermind, I just read your blog.

Thanks for the repo
