### ISSUE TITLE
output size of the converted model is wrong

### ISSUE THREAD

**Issue by roeiherz** [akirasosa/mobile-semantic-segmentation#44]
Hi,
I tried your coreml_converter.py script and the output layer (identifier 597) is:
      tensor_type {
        elem_type: FLOAT
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 224
          }
          dim {
            dim_value: 224
          }

The identifier is 597 and not 595 as you told because I used your **interpolate** layer (was in # in your original code):
        x = interpolate(x, scale_factor=2, mode='bilinear', align_corners=False) 

Now, I have two questions:
(1) why the output is 3x224x224 and not 1x224x224 ?
(2) the **interpolate** layer is getting error when I am trying to convert. Is there another way to upload from 112x112 to 224x224?

Thanks.

**Comment by hugoliv** [comment]
Hello,

I used Netron to explore the graph, I didn't connect the **interpolate** layer. The input_id is 0 and ouput_id is 590 but the shape is 1x112x112 and not 1x224x224.

<img width="1558" alt="Capture d’écran 2019-03-28 à 11 45 04" src="https://user-images.githubusercontent.com/4832281/55151883-7cd34e80-514f-11e9-8061-01b0f7baa8e3.png">

**Comment by akirasosa** [comment]
About 1. It's because iOS app requires 3 channels. So, I do it in model. It's also possible for you to write code in iOS which converts single channel to 3.

About 2, I don't have it in current code. It's not so difficult to show mask as twice large size in iOS.
