### ISSUE TITLE
image size not correct

### ISSUE THREAD

**Issue by noguxun** [akirasosa/mobile-semantic-segmentation#7]
#1 
document issue
the correct command line to set image size is 
python data.py --img_size=128
not 
python data.py --image_size=128

#2 
training issue
when data is generated with default size 192
I started train
and the training process got killed after log 
"
lr: 0.100000
Epoch 1/250
"

**Comment by akirasosa** [comment]
@noguxun 
> document issue

I fixed it. Thanks

> training issue

I can not reproduce it. For example, I tried it.
```
python train_full.py --img_file=data/images-192.npy --mask_file=data/masks-192.npy
```

It shows...
```
lr: 0.100000
Epoch 1/250
  2/146 [..............................] - ETA: 3293s - loss: -0.2054 - dice_coef: 0.2054 - recall: 0.3987 - precision: 0.1245 - b
inary_crossentropy: 0.6998
```

Do you have some more information?

**Comment by noguxun** [comment]
About #2, 
It might be just lacking of resource on my HW environment (old laptop, no GPU, 4G memory)
I am planning setting up a AWS instance to see if problem could go away.
